name: Release

on:
  pull_request:
    types:
    - closed
    branches: [ main, master ]

env:
  configuration: Release
  validRelease: contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == 'true'

jobs:
  release:
    runs-on: windows-latest

    steps:

    - name: test
      run: echo ${{env.validRelease}}
